###
GET http://localhost:3000/v1/

###
GET http://localhost:3000/v1/users
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjE2NTQ3MzE4LCJleHAiOjE2MTY3MjAxMTh9.IIMssGKt6ihAjjzoyq-7CBjhDJiNyYl2xvbUxRK4amU

###
POST http://localhost:3000/v1/users
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjE2NTQ3MzE4LCJleHAiOjE2MTY3MjAxMTh9.IIMssGKt6ihAjjzoyq-7CBjhDJiNyYl2xvbUxRK4amU
content-type: application/json

{
    "first_name": "",
    "last_name": "",
    "email": "adsfasfd",
    "role":"asdf"
}

###
POST http://localhost:3000/v1/login
content-type: application/json 

{
    "email": "shubhamyadav.70007@outlook.com",
    "password": "test@1234"
}

###
DELETE http://localhost:3000/v1/users/6043970ba2d2954b6c94f9fe
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjE1NTQwODMwLCJleHAiOjE2MTU3MTM2MzB9.0B0o8uIdnkWzjv91Rv_R8TK3qPbMI7jAgo6MzxVhJYE

###
PUT http://localhost:3000/v1/users/604cf54bb3376a62a1e6bc42
Authorization: token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUm9sZSI6ImN1c3RvbWVyIiwiaWF0IjoxNjE2NTQ3MzE4LCJleHAiOjE2MTY3MjAxMTh9.IIMssGKt6ihAjjzoyq-7CBjhDJiNyYl2xvbUxRK4amU
content-type: application/json

{
    "first_name": "doctor",
    "last_name": "lance",
    "email": "first@test.com",
    "password": "test@1234",
    "role":"customer"
}

###
POST http://localhost:3000/v1/signup
content-type: application/json

{
    "first_name": "shubham ",
    "last_name": "yadav",
    "email": "agent2@test.com",
    "password": "test@1234",
    "role":"customer"
}
